// app/page.tsx
import Link from 'next/link'
import { Button } from '@/components/ui/Button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card'
import { Play, Users, Award, Clock } from 'lucide-react'

export default function HomePage() {
  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="bg-gradient-to-r from-primary-600 to-primary-700 text-white py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h1 className="text-4xl md:text-6xl font-display font-bold mb-6">
              Master New Skills with
              <span className="block text-primary-200">AI-Powered Learning</span>
            </h1>
            <p className="text-xl md:text-2xl mb-8 text-primary-100 max-w-3xl mx-auto">
              Learn from expert-crafted video courses with personalized AI assessments 
              that adapt to your learning pace.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/courses">
                <Button size="lg" variant="secondary" className="min-w-40">
                  Browse Courses
                </Button>
              </Link>
              <Link href="/auth/signup">
                <Button size="lg" variant="outline" className="min-w-40 border-white text-white hover:bg-white hover:text-primary-600">
                  Get Started Free
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-display font-bold text-dark-900 mb-4">
              Why Choose LearnHub?
            </h2>
            <p className="text-lg text-dark-600 max-w-2xl mx-auto">
              Our platform combines expert instruction with cutting-edge AI to create 
              a personalized learning experience that adapts to you.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            <Card className="text-center border-0 shadow-lg">
              <CardHeader>
                <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Play className="w-6 h-6 text-primary-600" />
                </div>
                <CardTitle className="text-xl">Video Learning</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-dark-600">
                  High-quality video content from industry experts, organized in 
                  easy-to-follow learning paths.
                </p>
              </CardContent>
            </Card>

            <Card className="text-center border-0 shadow-lg">
              <CardHeader>
                <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Award className="w-6 h-6 text-primary-600" />
                </div>
                <CardTitle className="text-xl">AI Assessments</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-dark-600">
                  Smart tests generated by AI that adapt to your learning progress 
                  and ensure concept mastery.
                </p>
              </CardContent>
            </Card>

            <Card className="text-center border-0 shadow-lg">
              <CardHeader>
                <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Clock className="w-6 h-6 text-primary-600" />
                </div>
                <CardTitle className="text-xl">Progress Tracking</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-dark-600">
                  Detailed analytics and progress tracking to keep you motivated 
                  and on track with your goals.
                </p>
              </CardContent>
            </Card>

            <Card className="text-center border-0 shadow-lg">
              <CardHeader>
                <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Users className="w-6 h-6 text-primary-600" />
                </div>
                <CardTitle className="text-xl">Community</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-dark-600">
                  Join thousands of learners in our community and accelerate 
                  your growth through collaboration.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-dark-50">
        <div className="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl md:text-4xl font-display font-bold text-dark-900 mb-6">
            Ready to Start Learning?
          </h2>
          <p className="text-lg text-dark-600 mb-8">
            Join thousands of students who are already advancing their careers with LearnHub.
          </p>
          <Link href="/auth/signup">
            <Button size="lg" className="min-w-48">
              Start Learning Today
            </Button>
          </Link>
        </div>
      </section>
    </div>
  )
}